# Generated by Django 5.2.8 on 2025-12-03 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_campaigns', to=settings.AUTH_USER_MODEL)),
                ('players', models.ManyToManyField(blank=True, related_name='joined_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=1)),
                ('strength', models.IntegerField(default=10)),
                ('dexterity', models.IntegerField(default=10)),
                ('constitution', models.IntegerField(default=10)),
                ('intelligence', models.IntegerField(default=10)),
                ('wisdom', models.IntegerField(default=10)),
                ('charisma', models.IntegerField(default=10)),
                ('hp', models.IntegerField(default=0)),
                ('mana', models.IntegerField(default=0)),
                ('sanity', models.IntegerField(default=100)),
                ('notes', models.TextField(blank=True)),
                ('base_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.characterbase')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='campaigns.campaign')),
                ('char_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.class')),
                ('chosen_feature_options', models.ManyToManyField(blank=True, to='characters.featureoption')),
                ('chosen_features', models.ManyToManyField(blank=True, to='characters.feature')),
                ('lineage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.originlineage')),
                ('origin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.origin')),
                ('subclass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.subclass')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
