# Generated by Django 5.2.8 on 2025-12-04 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaigninvite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ability', models.CharField(choices=[('strength', 'Força'), ('dexterity', 'Destreza'), ('constitution', 'Constituição'), ('intelligence', 'Inteligência'), ('wisdom', 'Sabedoria'), ('charisma', 'Carisma')], max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='campaigncharacter',
            name='charisma',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='campaigncharacter',
            name='constitution',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='campaigncharacter',
            name='dexterity',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='campaigncharacter',
            name='intelligence',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='campaigncharacter',
            name='sanity',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='campaigncharacter',
            name='strength',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='campaigncharacter',
            name='wisdom',
            field=models.IntegerField(default=8),
        ),
        migrations.CreateModel(
            name='CharacterSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency_level', models.IntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='campaigns.campaigncharacter')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.skill')),
            ],
            options={
                'unique_together': {('character', 'skill')},
            },
        ),
    ]
