# Generated by Django 5.2.8 on 2025-12-15 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_skill_alter_campaigncharacter_charisma_and_more'),
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigncharacter',
            name='base_character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.characterbase'),
        ),
        migrations.AlterField(
            model_name='campaigncharacter',
            name='lineage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.originlineage'),
        ),
    ]
