# Generated by Django 5.2.8 on 2025-12-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_alter_campaigncharacter_base_character_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigncharacter',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Ativo'), ('dead', 'Morto'), ('retired', 'Aposentado'), ('removed', 'Removido')], default='draft', max_length=20),
        ),
    ]
