# Generated by Django 5.2.8 on 2025-12-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_campaignlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignlog',
            name='type',
            field=models.CharField(choices=[('status_change', 'Mudança de status'), ('character_created', 'Personagem criado'), ('character_removed', 'Personagem removido'), ('system', 'Sistema')], default='system', max_length=30),
        ),
    ]
